name: doctor_car
description: "Doctor Car - OBD-II Car Scanner & Diagnostics"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.70.2
  flutter_bluetooth_serial: ^0.4.0
  flutter_blue_plus: ^1.31.0
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
